import os

DMA_FUNC_ENUM_MAP = [
    "SYS_DMA_FUNC_UNSED",
    "SYS_DMA_FUNC_MAC_TX",
    "SYS_DMA_FUNC_MAC_RX",
    "SYS_DMA_FUNC_AES_IN",
    "SYS_DMA_FUNC_AES_OUT",
    "SYS_DMA_FUNC_AES_AUTH_IN",
    "SYS_DMA_FUNC_SHA",
    "SYS_DMA_FUNC_SPI0_TX",
    "SYS_DMA_FUNC_SPI0_RX",
    "SYS_DMA_FUNC_SPI1_TX",
    "SYS_DMA_FUNC_SPI1_RX",
    "SYS_DMA_FUNC_UART0_TX",
    "SYS_DMA_FUNC_UART0_RX",
    "SYS_DMA_FUNC_UART1_TX",
    "SYS_DMA_FUNC_UART1_RX",
    "SYS_DMA_FUNC_UART2_TX",
    "SYS_DMA_FUNC_UART2_RX",
    "SYS_DMA_FUNC_I2C0_TX",
    "SYS_DMA_FUNC_I2C0_RX",
    "SYS_DMA_FUNC_I2C1_TX",
    "SYS_DMA_FUNC_I2C1_RX",
    "SYS_DMA_FUNC_USER",
    "SYS_DMA_FUNC_MAX"
]

CATEGORY_RULES = [
    ("TARGET", ["TARGET_", "CONFIG_ER81", "WORKAROUND"]),
    ("DEVICE", ["ES_DEVICE_"]),
    ("UART CONFIG", ["UART",  "ES_UART", "ES_COMP_ENABLE_UART"]),
    ("DMA CONFIG", ["DMA_CH"]),
    ("RADIO CONFIG", ["RADIO", "ER81XX_MATCHING_FREQ"]),
    ("TIMER CONFIG", ["TIMER"]),
    ("SPI CONFIG", ["SPI"]),
    ("RTC CONFIG", ["RTC"]),
    ("I2C CONFIG", ["I2C"]),
    ("PWM CONFIG", ["PWM"]),
    ("PIO CONFIG", ["PIO"]),
    ("MIDDLEWARE CONFIG", ["MIDDLEWARE"]),
    ("MIDDLEWARE RETARGET", ["STDIO","PRINTF"]),
    ("MIDDLEWARE SHELL", ["SHELL"]),
]

def classify_define(symbol):
    for category, keys in CATEGORY_RULES:
        for key in keys:
            if symbol.startswith(key):
                return category
    return "OTHERS"

def parse_config_file(config_path):
    defines = []
    with open(config_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if line.startswith('CONFIG_'):
                name_value = line[len('CONFIG_'):]

                # Handle DMA CHx FUNC
                if name_value.startswith('DMA_CH') and '_FUNC=' in name_value:
                    symbol, value = name_value.split('=', 1)
                    try:
                        enum_index = int(value)
                        enum_name = DMA_FUNC_ENUM_MAP[enum_index]
                        defines.append( (symbol, f'#define {symbol} {enum_name} // {value}') )
                    except (ValueError, IndexError):
                        print(f"Warning: Invalid FUNC index {value} for {symbol}")
                    continue

                # Skip other DMA_CHx options
                if name_value.startswith('DMA_CH'):
                    continue

                if '=y' in name_value:
                    symbol = name_value.replace('=y', '')
                    defines.append( (symbol, f'#define {symbol} 1') )
                elif '=' in name_value:
                    symbol, value = name_value.split('=', 1)
                    defines.append( (symbol, f'#define {symbol} {value}') )
                elif 'is not set' in name_value:
                    symbol = name_value.split(' ')[0]
                    defines.append( (symbol, f'#undef {symbol}') )
    return defines

def generate_header(defines, output_path):
    categorized = {}

    for symbol, define_line in defines:
        category = classify_define(symbol)
        categorized.setdefault(category, []).append(define_line)

    with open(output_path, 'w') as f:
        f.write("/* Auto-generated by cfg_tool */\n")
        f.write("#ifndef _COMPONENTS_DEFAULT_H\n")
        f.write("#define _COMPONENTS_DEFAULT_H\n\n")

        for category, define_lines in categorized.items():
            f.write("/**\n")
            f.write(f" * ============================\n")
            f.write(f" *    {category}\n")
            f.write(f" * ============================\n")
            f.write(" */\n")
            for line in define_lines:
                f.write(line + "\n")
            f.write("\n")

        f.write("#endif /* _COMPONENTS_DEFAULT_H */\n")

def main():
    config_path = ".config"
    output_path = "components_xxxx.h"
    if not os.path.exists(config_path):
        print(f"Error: {config_path} not found")
        return
    defines = parse_config_file(config_path)
    generate_header(defines, output_path)
    print(f"Header generated at: {output_path}")

if __name__ == "__main__":
    main()

